### ISSUE TITLE
Sasl jaas config supporting

### ISSUE THREAD

**Issue by vinci7** [VanceLongwill/milena#9]
Hey, thanks for creating this useful tool!

I tried to consume my topic with sasl jass config but got the error, may I learn if it's possible to connect to the topic with sasl jaas config? 

Command
```
./milena consume \
  -b localhost:9092 \
  -t $TOPIC_NAME \
  -f $PATH_TO_DESC_FILE \
  -H $MESSAGE_NAME \
  -o=beginning
```

Error 
```
Error: Client config error: Java JAAS configuration is not supported, see https://github.com/confluentinc/librdkafka/wiki/Using-SASL-with-librdkafka for more information.
```

Thank you!

**Comment by VanceLongwill** [comment]
Thanks for reporting. I haven't tried this with SASL JASS but based on the link you'll need to provide the librdkafka options [here](https://github.com/confluentinc/librdkafka/wiki/Using-SASL-with-librdkafka#5-configure-kafka-client-on-client-host).

e.g. something like

```sh
./milena consume \
   -X security.protocol=SASL_PLAINTEXT \
   -X sasl.kerberos.keytab=/etc/security/keytabs/${CLIENT_NAME}.keytab \
   -X sasl.kerberos.principal=${CLIENT_NAME}/${CLIENT_HOST} \
   -X bootstrap.servers=localhost:9092 \
  -t $TOPIC_NAME \
  -f $PATH_TO_DESC_FILE \
  -H $MESSAGE_NAME \
  -o=beginning
```

Please note that the `-b` switch isn't supported so you have to pass it in with `-X bootstrap.servers=localhost:9092` as above. I'd accept an MR to add it though if you like. Otherwise connecting with milena should work identically to `kcat`.

Let me know if this works 🙏 

If it doesn't we might need to add the compile with the `gssapi` [feature flag from rust-rdkafka](https://github.com/fede1024/rust-rdkafka)

**Comment by VanceLongwill** [comment]
@vinci7 a friend of mine has tested SASL support with the latest release and it's working 🎉  on [the latest v0.1.6 release](https://github.com/VanceLongwill/milena/releases/tag/v0.1.6)

**Comment by VanceLongwill** [comment]
I also added the `-b` flag to match `kcat`
